name: Build tool NET Bundled non-single file

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
        dotnet build UndertaleModTool --no-restore
        dotnet build UndertaleModToolUpdater --no-restore
    - name: Publish Windows x86 NET Bundled
      run: |
        dotnet publish UndertaleModTool -c Release -r win-x86 --self-contained true -p:PublishSingleFile=false --output win_x86
        dotnet publish UndertaleModToolUpdater -c Release -r win-x86 --self-contained true -p:PublishSingleFile=false -p:PublishTrimmed=True -p:TrimMode=CopyUsed --output win_x86\Updater
    - name: Publish Windows x64 NET Bundled
      run: |
        dotnet publish UndertaleModTool -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false --output win_x64
        dotnet publish UndertaleModToolUpdater -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false -p:PublishTrimmed=True -p:TrimMode=CopyUsed --output win_x64\Updater
    - name: Copy external files
      run: |
        Copy-Item "README.md" -Destination "./win_x86/"
        Copy-Item "README.md" -Destination "./win_x64/"
        Copy-Item "SCRIPTS.md" -Destination "./win_x86/"
        Copy-Item "SCRIPTS.md" -Destination "./win_x64/"
    - name: Archive win_x86
      uses: actions/upload-artifact@v2
      with:
        name: win_x86
        path: win_x86
    - name: Archive win_x64
      uses: actions/upload-artifact@v2
      with:
        name: win_x64
        path: win_x64
