name: Build

on:
  workflow_dispatch:
    inputs:
      gui-single-file-config:
        required: false
        type: string
        default: "[ true, false ]"
      gui-bundled-config:
        required: false
        type: string
        default: "[ true, false ]"
      cli-bundled-config:
        required: false
        type: string
        default: "[ true, false ]"
  workflow_call:
    inputs:
      gui-single-file-config:
        required: false
        type: string
        default: "[ true, false ]"
      gui-bundled-config:
        required: false
        type: string
        default: "[ true, false ]"
      cli-bundled-config:
        required: false
        type: string
        default: "[ true, false ]"

jobs:
  prepare-matrix:
    name: Prepare matrix
    runs-on: ubuntu-latest
    outputs:
      gui-matrix: ${{ steps.set-matrix.outputs.gui-matrix }}
      cli-matrix: ${{ steps.set-matrix.outputs.cli-matrix }}
    steps:
    - id: set-matrix
      run: |
        echo "::set-output name=gui-matrix::{ \"single-file\": ${{ inputs.gui-single-file-config }}, \"bundled\": ${{ inputs.gui-bundled-config }} }"
        echo "::set-output name=cli-matrix::{ \"bundled\": ${{ inputs.cli-bundled-config }} }"

  gui:
    name: GUI
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix:
        rid: [ win-x64, win-x86 ]
        configuration: [ Debug ]
        include:
        - rid: win-x64
          os: windows-latest
        - rid: win-x86
          os: windows-latest
        - ${{ fromJson(needs.prepare-matrix.outputs.gui-matrix) }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish ${{ matrix.rid }}
      run: |
        dotnet publish UndertaleModTool -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=${{ matrix.single-file }} --output publish
        dotnet publish UndertaleModToolUpdater -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=false --output publish/Updater

    - name: Prepare artifact
      id: prepare-artifact
      shell: bash
      run: |
        cp ./README.md ./SCRIPTS.md ./LICENSE.txt ./publish
        echo "::set-output name=artifact_name::GUI-${{ matrix.rid }}$([[ ${{ matrix.bundled }} = true ]] && echo "-bundled")$([[ ${{ matrix.single-file }} = true ]] && echo "-singleFile")"
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prepare-artifact.outputs.artifact_name }}
        path: publish

  cli:
    name: CLI
    needs: prepare-matrix
    strategy:
      fail-fast: false
      matrix:
        rid: [ win-x64, win-x86, osx-x64, linux-x64 ]
        configuration: [ Debug ]
        include:
        - rid: win-x64
          os: windows-latest
        - rid: win-x86
          os: windows-latest
        - rid: osx-x64
          os: macOS-latest
        - rid: linux-x64
          os: ubuntu-latest
        - ${{ fromJson(needs.prepare-matrix.outputs.cli-matrix) }}
    runs-on: ${{ matrix.os }}

    if: matrix.bundled && inputs.cli-bundled || !matrix.bundled && inputs.cli-non-bundled

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Publish ${{ matrix.rid }}
      run: |
        dotnet publish UndertaleModCli -c ${{ matrix.configuration }} -r ${{ matrix.rid }} --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=false --output publish

    - name: Prepare artifact
      id: prepare-artifact
      shell: bash
      run: |
        cp ./README.md ./LICENSE.txt ./publish
        echo "::set-output name=artifact_name::CLI-${{ matrix.rid }}$([[ ${{ matrix.bundled }} = true ]] && echo "-bundled")"
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ steps.prepare-artifact.outputs.artifact_name }}
        path: publish
